### ISSUE TITLE
Usage of auto entities

### ISSUE THREAD

**Issue by SNoof85** [TBens/lovelace-ui-minimalist#1]
Not really an issue but an improvement...

On "consommation" dashboard. You can use the custom:auto-entities card to populate the grid for batteries. This avoids manual update of the dash if any new battery device shows up !
here is what i've done :
```
    - cards:
        - template: bordures
          type: 'custom:button-card'
        - type: 'custom:auto-entities'
          sort:
            method: state
            numeric: true
          card:
            type: grid
            columns: 2
            square: false
          card_param: cards
          filter:
            exclude: null
            include:
              - entity_id: sensor.*battery
                options:
                  type: 'custom:button-card'
                  template:
                    - icon_info_bg
                    - generique
              - entity_id: sensor.*netatmo*battery*
                options:
                  type: 'custom:button-card'
                  template:
                    - icon_info_bg
                    - generique
        - template: bordures
          type: 'custom:button-card'
      type: horizontal-stack
```

And adding the sort will show you the lowest battery level first !
